theme: jekyll-theme-minimal
description: Reference-free cell-type deconvolution of multi-cellular spatially resolved transcriptomics data 
logo: https://github.com/JEFworks/STdeconvolve/blob/package/docs/img/STdeconvolve_logo.png?raw=true